name: base
channels:
  - defaults
dependencies:
  - python=3.13
  - conda==25.5.1
  - setuptools
  - pip
  - wheel
  - conda-anaconda-telemetry[version='>=0.2.0']
  - conda-anaconda-tos[version='>=0.2.1']
  - conda-content-trust
  - conda-libmamba-solver
  - menuinst
  - anaconda-anon-usage
  - pip:
    - playwright==1.54.0
