name: Format & Lint

on: [push, pull_request]

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install tools
      run: |
        pip install black ruff

    - name: Run Black (check only)
      run: black .

    - name: Run Ruff (linter)
      run: ruff check --fix .
